# Generated by Django 3.0.4 on 2020-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='remark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
