# Generated by Django 3.0.4 on 2020-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0003_dailytask_totalhours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='totalHours',
            new_name='noOfHours',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='fromDateTime',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='toDateTime',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='partOfKra',
            field=models.BooleanField(default=False),
        ),
    ]
