# Generated by Django 3.0.4 on 2020-04-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsibility', models.CharField(max_length=500)),
                ('percentageWeight', models.IntegerField(null=True)),
                ('percentageAchieved', models.IntegerField(null=True)),
                ('successMeasured', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
                ('threshold', models.BooleanField()),
                ('developmentGoal', models.BooleanField()),
                ('gestalt', models.BooleanField()),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kras.Kra')),
            ],
        ),
    ]
