# Generated by Django 3.0.4 on 2020-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustrackeruser',
            name='leavebalance',
            field=models.IntegerField(blank=True),
        ),
    ]
