# Generated by Django 3.0.4 on 2020-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyusers', '0003_remove_statustrackeruser_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustrackeruser',
            name='leavebalance',
            field=models.IntegerField(null=True),
        ),
    ]
