# Generated by Django 3.0.4 on 2020-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyusers', '0005_statustrackeruser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustrackeruser',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
