# Generated by Django 3.0.4 on 2020-04-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyusers', '0006_statustrackeruser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statustrackeruser',
            name='username',
        ),
    ]
