# Generated by Django 3.0.4 on 2020-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
