# Generated by Django 3.0.4 on 2020-04-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatus', '0002_auto_20200421_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatus',
            name='status',
        ),
    ]
