# Generated by Django 3.0.4 on 2020-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatus', '0003_remove_dailystatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatus',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
