# Generated by Django 3.0.4 on 2020-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatus', '0004_dailystatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
